2025-09-17 13:41:53.130227+08:00 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at com.alibaba.cloud.ai.manus.tool.database.DataSourceService.getConnection(DataSourceService.java:90)
	at com.alibaba.cloud.ai.manus.tool.database.DatabaseUseTool.getCurrentToolStateString(DatabaseUseTool.java:234)
	at com.alibaba.cloud.ai.manus.agent.DynamicAgent.collectEnvData(DynamicAgent.java:552)
	at com.alibaba.cloud.ai.manus.agent.DynamicAgent.collectAndSetEnvDataForTools(DynamicAgent.java:570)
	at com.alibaba.cloud.ai.manus.agent.DynamicAgent.think(DynamicAgent.java:127)
	at com.alibaba.cloud.ai.manus.agent.ReActAgent.step(ReActAgent.java:83)
	at com.alibaba.cloud.ai.manus.agent.BaseAgent.run(BaseAgent.java:222)
	at com.alibaba.cloud.ai.manus.runtime.executor.AbstractPlanExecutor.executeStep(AbstractPlanExecutor.java:109)
	at com.alibaba.cloud.ai.manus.runtime.executor.AbstractPlanExecutor.lambda$0(AbstractPlanExecutor.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
